name: UI Docker Image CI

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
    paths:
      -'*/DemoApp/*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.7.0
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./DemoApp/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/demoapp:latest
